# **Use Text Files**

In [0]:
# I want to use file.txt , i want to read what has it contain

with open("/Workspace/Databricks_Bootcamp/silver_layer/file.txt" , "r") as file:
    content =  file.read()
    # print(file.read())
print(content)

Hello Aakash Tyagi

In [0]:
#  If you dont have the file , and you want to create it 

with open("/Workspace/Databricks_Bootcamp/silver_layer/Create.txt" , "w") as file2:
    file2.write("hello world")

## Python file

In [0]:
with open("/Workspace/Databricks_Bootcamp/silver_layer/Pythonfile.py" , "w") as file3:
    file3.write("my_screte = '1234'")

In [0]:
import Pythonfile

In [0]:
Pythonfile.my_screte

'1234'

### **JSON FILES**

In [0]:
import pandas as pd
with open("/Workspace/Databricks_Bootcamp/silver_layer/mapping.json" ,"r") as j:
    df = pd.read_json(j)
df

   id name
0   1   aa
1   2   bb
2   3   cc
3   4   dd
4   5   ee

In [0]:
df = pd.read_json("/Workspace/Databricks_Bootcamp/silver_layer/mapping.json")
df

   id name
0   1   aa
1   2   bb
2   3   cc
3   4   dd
4   5   ee

## Convert it into  pyspark dataframe

In [0]:
df_pyspark = spark.createDataFrame(df)
display(df)

id,name
1,aa
2,bb
3,cc
4,dd
5,ee